Loading module miniconda version 23.1.0-1
Traceback (most recent call last):
  File "get_linear_probe_data.py", line 108, in <module>
    main(config)
  File "get_linear_probe_data.py", line 83, in main
    feature_path = glob.glob(model_dir+feature_dirs[i]+features_string + "/*.csv")[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "run_linear_pipeline.py", line 9, in <module>
    subprocess.check_call(['python', script, '-c', 'config.yaml'])
  File "/nvme_scratch1/cjh86475/conda_envs/aiml_active_learning_almo_all/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'get_linear_probe_data.py', '-c', 'config.yaml']' returned non-zero exit status 1.
